name: Rust

on:
  push:
    branches:    
      - master

jobs:
  build-windows:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: src/rustnes/cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      
  build-linux:
    runs-on: ubuntu-18.04
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
